language: node_js
node_js:
- lts/*
before_install:
- npm install -g npm
- npm install -g grunt-cli
notifications:
  email:
    on_success: change
    on_failure: change
sudo: required
cache:
  directories:
  - node_modules
addons:
  chrome: stable
deploy:
  provider: npm
  email: stdavis@utah.gov
  api_key:
    secure: ELjXmFnvKy8mZIIG0s0bVIz91Nl8qfvr8esOUEDTV5luyhxo1srEIrvs1oCbWJ4Lw04aEWuH49XB82wZ5xO2BYGCweGIpZ3w2PxTFJbPd/5xu0XjVNqxEBbnNrMzXIWynTsU24HhwHHBfS/xFJp0MmoASn2Rl/ZzJN4TusetH9WV+8hyrZQ8eiefdC6FQZHkz3JHqzjZebgb+mEq92Oh3uOkfpFm6lJ79hKfuj4hPF41gZAck1myEsBwuF4El3u6BxZA05DLmEzICy3YvWCRtoqL4XC00yGiZW98JXbEFj7dWC8rUWL/Fe3DDQUX8VsaxsVJT+IE1PymKqMPdYj0GQs86QKTMROa4ytBFiBrsu2YVn7P/+4dsLyreSTA7k3mWH5JY+AC+6IF9yC/UnxumxT74zvP7ztWSy8swuFvY8+gkyAGH+I+jBB8tPWsdhsBfSWcOh95M5YCEQmD7g0zuGhQStOYOkypAclNaC3jgrjyLgOOoGEoz8v5wdEjmWoqFLnbmwQvZcpag6TwhCp7X4S7Xc8rMcl4RQmshds7HIeTFN/k9qStJlBQ2PS6iNNzJWzC4Cdt/gVkirtKXlJ3C9b1piuuTV24n8/bsocvSn4D2YVmERaZHRcJzuVfPnfdB3BM5s5rnB5NQs5nG2PTxrhl90LqPpjksJhPX0SesZk=
  on:
    tags: true
    repo: agrc-widgets/layer-selector
